nelmio_api_doc:
    documentation:
        info:
            title: Pharmacy API
            description: API documentation for Pharmacy App
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api
